image: drupalpod/drupalpod-gitpod-base:latest

tasks:
  - name: Setup
    init: |
      ddev start -y
      ddev composer install
      ddev drush site:install --yes --account-pass admin --site-name="Drupal" demo_umami --db-url=mysql://db:db@db:3306/db
  - name: Open Browser
    command: |
      gp sync-await setup
      ddev start -y
      gp preview $(gp url 8080)
      ddev drush uli
ports:
  - port: 3306
    onOpen: ignore
  - port: 6942
    onOpen: ignore
  # Used by MailHog
  - port: 8027
    onOpen: ignore
  # Used by phpMyAdmin
  - port: 8036
    onOpen: ignore
  # Direct-connect ddev-webserver port that is the main port
  - port: 8080
    onOpen: ignore
  # Ignore host https port
  - port: 8443
    onOpen: ignore
  # xdebug port
  - port: 9003
    onOpen: ignore
  - port: 9999
    onOpen: open-browser
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true

