image: drupalpod/drupalpod-gitpod-base:latest

tasks:
  - name: Setup
    init: |
      ddev start -y
      ddev composer install
      ddev drush site:install --yes --account-pass admin --site-name="Drupal" umami --db-url=mysql://db:db@db:3306/db
  - name: Open Browser
    command: |
      ddev start -y
      gp ports await 8080 && gp preview $(gp url 8080)
ports:
  - port: 3306
    onOpen: ignore
  # Used by MailHog
  - port: 8027
    onOpen: ignore
  # Used by phpMyAdmin
  - port: 8036
    onOpen: ignore
  # Direct-connect ddev-webserver port that is the main port
  - port: 8080
    onOpen: ignore
    visibility: public
  # Ignore host https port
  - port: 8443
    onOpen: ignore
  # xdebug port
  - port: 9003
    onOpen: ignore
