<?php

/**
 * @file
 * Functions to support theming in the Particle theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function particle_preprocess_html(array &$variables): void {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function particle_preprocess_page(array &$variables): void {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function particle_preprocess_node(array &$variables): void {

}
